#!/usr/bin/perl

$uname=`uname`;
chomp $uname;
print STDERR "Macintosh detected.\n" if $uname eq 'Darwin';

open(NM,'nm -g `find . -name *.o`|');
while (<NM>) {
  chomp;
  if (/^[\.\/]+(([a-z]+\/).*_a-)?(.*)\.o:/) {
    $fn="$2$3.c";
    print "$_ => $fn\n";
  } elsif (/^([0-9a-f]*)\s+([A-RT-Z]) (.*)$/) {
    $two=$2;
    $three=$3;
    $three=~s/^_// if $uname eq 'Darwin';
    if ($two eq 'U') {
      $extern_used{$three}=1;
    } else {
      $extern_defined{$three}=$fn;
    }
  }
}
close(NM);

@questionable_externs=();
foreach $extern (sort keys %extern_defined) {
  if (!$extern_used{$extern}) {
    push @questionable_externs,$extern;
  }
}

while (<*/*.[ch]>) {
  $fn=$_;
  print "($fn)\n";
  %static_defined=();
  open(SRC,$fn);
  while (<SRC>) {
    if (/\s*static\b[^(=]*\s([A-Z_][A-Za-z_0-9]*)\s*[(,;=]/) {
      $static_defined{$1}=1;
    }
  }
  close(SRC);
  %static_used=();
  @statics=sort keys %static_defined;
  open(SRC,$fn);
  while (<SRC>) {
    foreach $symbol (@statics) {
      if (/\b$symbol\b/) {
        $static_used{$symbol}++;
      }
    }
    foreach $extern (@questionable_externs) {
      if ($extern_defined{$extern} eq $fn) {
        if (/\b$extern\b/) {
          $extern_used{$extern}++;
        }
      }
    }
  }
  close(SRC);
  foreach $symbol (@statics) {
    if ($static_used{$symbol}<2) {
      print "$fn defines static $symbol but does not use it\n";
    }
  }
}

foreach $extern (@questionable_externs) {
  if ($extern_used{$extern}<2) {
    print $extern_defined{$extern}.
      " defines extern $extern but no file uses it\n";
  }
}
