#!/bin/bash

mkdir -p dat
for fn in Blocks.txt ; do \
  wget -N -nd -P dat http://unicode.org/Public/UCD/latest/ucd/$fn ; \
done

wget -N -nd -P dat \
  http://unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0201.TXT
wget -N -nd -P dat \
  http://unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT
wget -N -nd -P dat \
  http://unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/KSC/KSC5601.TXT
wget -N -nd -P dat \
  http://unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/KSC/JOHAB.TXT

mkdir -p dat/apple
wget -N -nd -P dat/apple -r -l1 -np \
  http://www.unicode.org/Public/MAPPINGS/VENDORS/APPLE/
rm -f dat/apple/index* dat/apple/robots*

mkdir -p dat/adobe
wget -N -nd -P dat/adobe -r -l1 -np \
  http://www.unicode.org/Public/MAPPINGS/VENDORS/ADOBE/
rm -f dat/adobe/index* dat/adobe/robots*
