#!/bin/bash

mkdir -p unicode
for fn in Blocks.txt ; do \
  wget -N -nd -P unicode http://unicode.org/Public/UCD/latest/ucd/$fn ; \
done

mkdir -p unicode/apple
wget -N -nd -P unicode/apple -r -l1 -np \
  http://www.unicode.org/Public/MAPPINGS/VENDORS/APPLE/
rm -f unicode/apple/index* unicode/apple/robots*

mkdir -p unicode/adobe
wget -N -nd -P unicode/adobe -r -l1 -np \
  http://www.unicode.org/Public/MAPPINGS/VENDORS/ADOBE/
rm -f unicode/adobe/index* unicode/adobe/robots*
