#!/usr/bin/perl -CDS

#
# Copyright notice checker
# Copyright (C) 2012  Matthew Skala
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# As a special exception, if you create a document which uses this font, and
# embed this font or unaltered portions of this font into the document, this
# font does not by itself cause the resulting document to be covered by the
# GNU General Public License. This exception does not however invalidate any
# other reasons why the document might be covered by the GNU General Public
# License. If you modify this font, you may extend this exception to your
# version of the font, but you are not obligated to do so. If you do not
# wish to do so, delete this exception statement from your version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Matthew Skala
# http://ansuz.sooke.bc.ca/
# mskala@ansuz.sooke.bc.ca
#

# there may be SVN-controlled versions that were never public...
$earliest=2011;
$bywhom='Matthew Skala';

$files=`svn list -R`;

foreach $file (split("\n",$files)) {
  next if $file=~m!/$!;
  next if $file=~m!\.pdf$!;
  next if $file=~m!\.gz$!;
  next if $file=~m!\.pfb$!;
  next if $file=~m!\.otf$!;
  next if $file=~m!genjimon/!;
  $earliest=($file=~/idsgrep\//)?2012:2011;
  %years=();
  $_=`svn log $file`;
  while (/^r\d+ \| [a-z0-9]+ \| (\d{4})-\d+-\d+ /mg) {
    $years{$1}=1 if $1>=$earliest;
  }
  $ylist=join(', ',sort keys %years);
  $flagged=0;
  open(F,$file);
  while (<F>) {
    if (/^([ !-\/:-@[-`{-~]*)Copyright (\(C\)|\x{00A9})([0-9, ]+)$bywhom/
      && ($3 ne " $ylist  ")) {
      if (!$flagged) {
        print "$file:\n";
        $flagged=1;
      }
      print;
    }
  }
  close(F);
  if ($flagged) {
    print "=> $ylist\n\n";
  }
}
