#!/usr/bin/perl -CDS

#
# Copyright notice checker
# Copyright (C) 2012, 2013  Matthew Skala
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# As a special exception, if you create a document which uses this font, and
# embed this font or unaltered portions of this font into the document, this
# font does not by itself cause the resulting document to be covered by the
# GNU General Public License. This exception does not however invalidate any
# other reasons why the document might be covered by the GNU General Public
# License. If you modify this font, you may extend this exception to your
# version of the font, but you are not obligated to do so. If you do not
# wish to do so, delete this exception statement from your version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Matthew Skala
# http://ansuz.sooke.bc.ca/
# mskala@ansuz.sooke.bc.ca
#

# there may be SVN-controlled versions that were never public...
$earliest=2011;
$bywhom='Matthew Skala';

$files=`svn list -R`;

foreach $file (split("\n",$files)) {
  next if $file=~m!/$!;
  next if $file=~m!\.gz$!;
  next if $file=~m!\.otf$!;
  next if $file=~m!\.pdf$!;
  next if $file=~m!\.pfb$!;
  next if $file=~m!\.png$!;
  next if $file=~m!genjimon/!;
  %years=();
  $_=`svn log $file`;
  while (/^r\d+ \| [a-z0-9]+ \| (\d{4})-\d+-\d+ (.*?)----/msg) {
    $thisyear=$1;
    $message=$2;
    $years{$thisyear}=1 if ($message!~/copyright/i)
      || ($message=~/small but global/);
  }
  $ylist=join(', ',sort keys %years);
  $flagged=0;
# print "$file\n";
  open(F,$file);
  while (<F>) {
    if (/^([ !-\/:-@[-`{-~]*)Copyright (\(C\)|\x{00A9})([0-9, ]+)$bywhom/) {
      $nylist=$3;
      $earliest=9999; # beware the Y10K problem
      foreach $year (split(/, /,$nylist)) {
        $earliest=$year if $year<$earliest;
      }
      %myyears=();
      foreach $year (keys %years) {
        $myyears{$year}=1 if $year>=$earliest;
      }
      $ylist=join(', ',sort keys %myyears);
      if ($nylist ne " $ylist  ") {
        if (!$flagged) {
          print "$file:\n";
          $flagged=1;
        }
        print;
      }
    }
  }
  close(F);
  if ($flagged) {
    print "=> $ylist\n\n";
  }
}
