#!/usr/bin/perl -CDS

use utf8;

$update_time=`date`;

$style=shift;
$late_eval='';

$this_pkg_link='';

open(RLC,'reflog.php');
while (<RLC>) {
  $reflog_code.=$_;
}
close(RLC);

while (<>) {
  chomp;
  if (/^([a-z0-9\-_]+)(\[.*?\])?:\s*(.*)$/i) {
    $key=lc($1);
    $style_pat=$2;
    $value=$3;
    $key=~s/-/_/g;
    if (($style_pat eq '') || ($style=~/$style_pat/)) {
      $v{$key}=$value;
    }
  } elsif (/^([a-z0-9\-_]+)(\[.*?\])?\.\s*$/i) {
    $key=lc($1);
    $style_pat=$2;
    $key=~s/-/_/g;
    $value='';
    while (<>) {
      last if $_ eq ".\n";
      s/^\.//;
      $value.=$_;
    }
    if (($style_pat eq '') || ($style=~/$style_pat/)) {
      $v{$key}=$value;
    }
  } elsif (/^EVAL\s*(.*)$/) {
    eval $1;
  } elsif (/^LATE-EVAL\s*(.*)$/) {
    $late_eval.=$1;
  }
}

$this_pkg_link='';
open(REL,'releases.rss');
$release_news='';
while (<REL>) {
  $date=$1 if /<pubDate>.* (\d+ [A-Z][a-z][a-z] 20\d\d) /;
  $link=$1 if m!<link>(.*?)</link>!;
  $heading=$2 if m!<title>(\([A-Z]\)\s+)?(.*?)</title>!;
  if (m!</item>!) {
    $release_news.=<<EOF;
<a href="$link" class="newsHeading">$heading</a>
<p class="newsDate">$date</p>
EOF
    $vf=$v{filename};
    if (($heading=~/$vf/i) ||
        (($this_pkg_link eq '') && ($heading=~/complete package/i))) {
      $heading=~s/Parasite font packages - //;
      $tpl_pat="($link\\S+)";
      $tpl_pat=~s/releases/downloads/;
      $this_pkg_head=$heading;
      $this_pkg_date=$date;
      $this_pkg_link=$link if $heading!~/complete package/i;
    }
  }
}
close(REL);

open(REL,'release-dump.txt');
while (<REL>) {
  $demourl=$1 if m!(http://osdn\S+demo.pdf/)!;
  $kcurl=$1 if m!(http://osdn\S+kanjichart.pdf/)!;
  $this_pkg_link=$1 if m!$tpl_pat! && ($this_pkg_link eq '');
}
close(REL);

open(KC,'../doc/kanjichart.tex');
$kcstat_en="<table>\n";
$kcstat_ja="<table>\n";
while (<KC>) {
  $flag=1 if /Mysterious/;
  s/\\,//g;
  if (/^\\section\*\{(.*)　(.*)　(\d+)\/(\d+)\}$/) {
    if ($flag) {
      $otherkanji+=$3;
    } else {
      $kcstat_en.="  <tr><td>$2</td><td>$3&nbsp;/&nbsp;$4</td></tr>\n";
      $kcstat_ja.="  <tr><td>$1</td><td>$3&nbsp;/&nbsp;$4</td></tr>\n";
    }
  }
}
$kcstat_en.="<tr><td>Other</td><td>$otherkanji</td></tr>\n</table>\n";
$kcstat_ja.="<tr><td>外の漢字</td><td>$otherkanji</td></tr>\n</table>\n";
close(KC);

eval $late_eval;

print <<EOF;
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="$v{lang}" lang="$v{long_lang}">
  <head>
    <meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
    <meta name="author" content="mskala@ansuz.sooke.bc.ca" />

    <link rel="stylesheet" type="text/css" href="./prosimii-screen.css" media="screen, tv, projection" title="Default" />
    <link rel="stylesheet alternative" type="text/css" href="./prosimii-print.css" media="screen" title="Print Preview" />
    <link rel="stylesheet" type="text/css" href="./prosimii-print.css" media="print" />

    <title>$v{title}</title>
  </head>

  <body>
    <!-- For non-visual user agents: -->
      <div id="top"><a href="#main-copy" class="doNotDisplay doNotPrint">Skip to main content.</a></div>

    <!-- ##### Header ##### -->

    <div id="header">
      <div class="superHeader">
        <a href="http://osdn.jp/" title="Hosted by SourceForge.JP">SourceForge.JP</a> |
        <a href="./$v{filename}.php.$v{other_lang}" title="$v{other_lang_title}"><img src="$v{other_lang_flag}" />&nbsp;$v{other_lang_title}</a>
      </div>

      <div class="midHeader">
        <h1 class="headerTitle">$v{title}</h1>
        <div class="headerSubTitle">
          $v{subtitle}
        </div>

        <br class="doNotDisplay doNotPrint" />

      </div>

      <div class="subHeader">
        <span class="doNotDisplay">Navigation:</span>
$v{nav_bar}
      </div>
    </div>

    <!-- ##### Main Copy ##### -->

    <div id="main-copy">
      <div class="rowOfBoxes">
        <div class="twoThirds noBorderOnLeft">
$v{main_text}
        </div>

        <div class="oneThird">
$v{right_side}
          <p class="filler"><!-- Filler para to extend left vertical line --></p>
        </div>
      </div>

      <div class="rowOfBoxes dividingBorderAbove">
        <div class="quarter noBorderOnLeft">
$v{bottom_one}
        </div>

        <div class="quarter">
$v{bottom_two}
          <p class="filler"><!-- Filler para to extend left vertical line --></p>
        </div>

        <div class="quarter">
$v{bottom_three}
          <p class="filler"><!-- Filler para to extend left vertical line --></p>
        </div>

        <div class="quarter">
$v{bottom_four}
          <p class="filler"><!-- Filler para to extend left vertical line --></p>
        </div>
      </div>
    </div>

    <!-- ##### Footer ##### -->

    <div id="footer">
$v{footer}
    </div>
  </body>
</html>
$reflog_code
EOF
